"use client";

import { ArrowRightLeft } from "lucide-react";
import { useEffect, useState } from "react";
import { AppShell } from "@/components/app-shell";
import { authFetch } from "@/lib/auth";

type Run = { id: string; filename: string; created_at: string; status: string };
type Holding = { isin: string; security_name?: string; quantity_delta?: number };
type Comparison = { changes: { portfolio_value: number; holdings: number; risk_score: number; added: Holding[]; removed: Holding[]; changed: Holding[] } };
export function CompareView() {
  const [runs, setRuns] = useState<Run[]>([]); const [older, setOlder] = useState(""); const [newer, setNewer] = useState(""); const [result, setResult] = useState<Comparison | null>(null); const [error, setError] = useState("");
  useEffect(() => { authFetch("/api/dashboard").then(r => r.json()).then(d => { const complete = d.recent_analyses.filter((r: Run) => r.status === "complete"); setRuns(complete); if (complete.length > 1) { setNewer(complete[0].id); setOlder(complete[1].id); } }); }, []);
  async function compare() { setError(""); const r = await authFetch("/api/analyses/compare", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ older_id: older, newer_id: newer }) }); const d = await r.json(); if (!r.ok) return setError(d.detail); setResult(d); }
  return <AppShell><div className="mx-auto max-w-5xl px-4 py-8 md:px-8"><p className="text-[9px] font-bold uppercase tracking-[1.5px] text-muted-text">Portfolio history</p><h1 className="mt-1 text-3xl font-bold text-[#173337]">Compare portfolios</h1><p className="mt-2 text-sm text-muted-text">See exactly what changed between any two saved analyses.</p>
    <section className="mt-7 rounded-xl border border-line bg-white p-5"><div className="grid gap-4 md:grid-cols-[1fr_auto_1fr_auto]"><select className="h-11 rounded-lg border border-line px-3 text-sm" value={older} onChange={e => setOlder(e.target.value)}><option value="">Older portfolio</option>{runs.map(r => <option key={r.id} value={r.id}>{new Date(r.created_at).toLocaleDateString()} — {r.filename}</option>)}</select><ArrowRightLeft className="self-center text-teal"/><select className="h-11 rounded-lg border border-line px-3 text-sm" value={newer} onChange={e => setNewer(e.target.value)}><option value="">Newer portfolio</option>{runs.map(r => <option key={r.id} value={r.id}>{new Date(r.created_at).toLocaleDateString()} — {r.filename}</option>)}</select><button className="primary-button" disabled={!older || !newer || older === newer} onClick={compare}>Compare</button></div>{error && <p className="mt-3 text-xs text-red-700">{error}</p>}</section>
    {result && <section className="mt-5 space-y-4"><div className="grid gap-3 sm:grid-cols-3">{[["Portfolio value", result.changes.portfolio_value], ["Holdings", result.changes.holdings], ["Risk score", result.changes.risk_score]].map(([label, value]) => <div key={String(label)} className="rounded-xl border border-line bg-white p-5"><span className="text-xs text-muted-text">{label}</span><strong className={`mt-2 block text-2xl ${Number(value) > 0 ? "text-amber" : "text-green"}`}>{Number(value) > 0 ? "+" : ""}{label === "Portfolio value" ? `₹${Number(value).toLocaleString("en-IN", { maximumFractionDigits: 0 })}` : Number(value).toFixed(label === "Holdings" ? 0 : 2)}</strong></div>)}</div>{([{ label: "Added holdings", rows: result.changes.added }, { label: "Removed holdings", rows: result.changes.removed }, { label: "Changed holdings", rows: result.changes.changed }]).map(({ label, rows }) => <div key={label} className="rounded-xl border border-line bg-white p-5"><h2 className="font-bold text-[#173337]">{label} ({rows.length})</h2><div className="mt-3 divide-y divide-line">{rows.length ? rows.map((row, index) => <div key={row.isin ?? index} className="flex justify-between py-3 text-xs"><span>{row.security_name}</span><span className="text-muted-text">{row.quantity_delta !== undefined ? `Quantity ${row.quantity_delta > 0 ? "+" : ""}${row.quantity_delta}` : row.isin}</span></div>) : <p className="py-3 text-xs text-muted-text">No changes in this category.</p>}</div></div>)}</section>}
  </div></AppShell>;
}
